Rendering
pod1425/peaengine pull request #5
Opened 2024-05-28 08:44 UTC by QinomeD

Sprite can be rendered, example in my playground

2024-05-31 17:25 UTC, pod1425 requested changes

2024-05-31 17:25 UTC, pod1425 commented on src/main/java/net/pod/peaengine/Engine.java
> +        textureLoader = new TextureLoader();
Why not make it static?

2024-05-31 17:25 UTC, pod1425 commented on src/main/java/net/pod/peaengine/render/texture/SpriteRegistry.java
> +package net.pod.peaengine.render.texture;
Please add a private default constructor and a way go get registry entries

2024-05-31 17:25 UTC, pod1425 commented on src/main/java/net/pod/peaengine/render/texture/SpriteRegistry.java
> +package net.pod.peaengine.render.texture;
It would also be good to make a base class Registry<> to avoid repeated code in future

2024-05-31 17:25 UTC, pod1425 commented on src/main/java/net/pod/peaengine/render/texture/TextureLoader.java
> +    private HashMap<String, Texture> textures = new HashMap<>();
Whats this for? I thought we use registry for this

2024-06-12 15:14 UTC, QinomeD commented
I hope it's good now

2024-06-14 07:43 UTC, pod1425 approved these changes

2024-06-14 07:43 UTC, pod1425 commented on src/main/java/net/pod/peaengine/playground/qinomed/BetterPlayground.java
Just a note: You can actually name your class Playground as its classpath is different (its in another package)

2024-06-14 07:44 UTC, merged